name: Draw Keymap (corne-eyelash)
on:
  workflow_dispatch:
  push:
    paths:
      - "zmk/corne-eyelash/config/**"
      - ".github/workflows/zmk-corne-eyelash-draw.yml"
      - "zmk/corne-eyelash/keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "zmk/corne-eyelash/config/*.keymap"
      config_path: "zmk/corne-eyelash/keymap_drawer.config.yaml"
      output_folder: "zmk/corne-eyelash/keymap-drawer"
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: true