name: Build ZMK firmware (corne-eyelash)
on:
  workflow_dispatch:
  push:
    paths:
      - "zmk/corne-eyelash/build.yaml"
      - "zmk/corne-eyelash/config/**"
      - "zmk/corne-eyelash/boards/**"
      - "zmk/corne-eyelash/zephyr/**"
      - ".github/workflows/zmk-corne-eyelash-build.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: zmk/corne-eyelash/build.yaml
      config_path: zmk/corne-eyelash/config